### ISSUE TITLE
Build fails on Xcode 7.3

### ISSUE THREAD

**Issue by flammable** [sheagcraig/yo#10]
I just updated to today's changes, and I'm getting an error and a bunch of warnings in Xcode.  Attaching a screenshot.

Feeling pretty dumb for updating to Xcode 7.3 (now that building yo works on Xcode 7.1), sorry for the bug report!

<img width="1512" alt="screen shot 2016-03-23 at 4 05 59 pm" src="https://cloud.githubusercontent.com/assets/8499030/13999165/55921d48-f111-11e5-9c87-d44e6501829d.png">

**Comment by flammable** [comment]
Oh, and the only thing I did was replace the icon (per the instructions in the ReadMe).

**Comment by tulgeywood** [comment]
@flammable I was about to post the same thing

**Comment by sheagcraig** [comment]
Yeehaw! Swift 2.2! I guess this is the fun that you experience when dealing with an actively developed language.

yo uses the CommandLine swift project to provide, you guessed it, commandline parsing. This dependency is wearing on me, however, so at some point I may rewrite it to just parse the commandline in yo itself. It was expedient at the time, but it does mean having to keep updating the included code (especially because I can never seem to get it to work as just a bundled Framework).

Anyway-give it a go now and let me know if it doesn't work. I only just installed Xcode 7.3 yesterday!

**Comment by flammable** [comment]
It works!  Thank you so much!

This is awesome! :trophy:
