### ISSUE TITLE
Build fails in Xcode 6.3 (6D570)

### ISSUE THREAD

**Issue by ehemmete** [sheagcraig/yo#3]
I was playing with adding a new icon, and when I try to build I get this error:
/Users/eric/Development/yo/yo/YoCommandLine.swift:10:8: Module file was created by an older version of the compiler: /Users/eric/Development/yo/CommandLine.framework/Modules/CommandLine.swiftmodule/x86_64.swiftmodule

From a quick Google, this seems to be related to the updated version of Xcode vs. the one where the project was created.

**Comment by sheagcraig** [comment]
@ehemmete Indeed, this is something I didn't plan on.

The framework that does the commandline argument handling was compiled on an older version, and is included as a compiled framework. I'm planning on handling the commandline arguments without this framework when I get a chance to work on it for the next release. At the very least, I need to just include the source so that this error does occur.

You can check out [CommandLine](https://github.com/jatoben/CommandLine) and build it, and replace the framework in yo with the product of that build if you're eager to just get it working. Otherwise, it's going to be a little bit before I can get to this.

**Comment by ehemmete** [comment]
Excellent! thank you for the quick response.  Love the idea for yo.  Will continue to try it out.

**Comment by tulgeywood** [comment]
Would love to see this update. Also if at all possible would be immensely useful to be able to execute bash on the -a flag.

**Comment by sheagcraig** [comment]
@ehemmete Give it a go now. I've undone the commandline as a framework approach, so it gets built along with the yo code now.
@tulgeywood I'll open an issue for you about this. Be forewarned, it will mean very careful escaping to pack a bash script into an argument!
