### ISSUE TITLE
Support timeout

### ISSUE THREAD

**Issue by frakman1** [sheagcraig/yo#43]
Currently, the notification remains on-screen indefinitely until I close it by pressing the "Close" button. 

It would be nice if there was a time-out command-line option that allows me to auto-dismiss it after a configurable amount of time. The [project](https://github.com/vjeantet/alerter) `alerter`  supports this feature. I would have used `alerter` except it doesn't allow for a custom icon to replace the ugly terminal default icon.

**Comment by sheagcraig** [comment]
@frakman1 unfortunately you're again dealing with the OS here. So that's why some notification tools just create their own dialogs and system; the macOS notification system is entirely controlled by Apple. Even then, our ability to consistently put buttons on and keep a notification persistent are due to using a private API that we're not supposed to know about.

It would be nice if we got more control, then it would be possible to make a one-notification-to-rule-them-all tool! Sorry!
